### PR TITLE
face angle as rotation matrix

### PR DESCRIPTION
**Pull request by ButzYung**
The routine to calculate face rotation is changed using the meothod introduced here.

http://renderdan.blogspot.com/2006/05/rotation-matrix-from-axis-vectors.html

This method returns a rotation matrix instead of roll/pitch/yaw angles. I didn't do the angle conversions beyond the matrix since it would require some extra math functions. In most cases you can just use the matrix directly for rotation so it shouldn't be a problem anyways. But if there is such a need for the angles we can do it.

`meshRaw` is also updated as it is required by this new method.

There is still a minor issue here though. For some reasons the rotation is inverted (at least this is the case when I use it in `three.js`). You can easily invert the rotation so it shouldn't be a big problem. Messing with the input coordinates seem will screw up the outputs which only makes things more complicated, and besides I am not good at this kind of math, so I think I will just leave it here in its simplest form. Feel free to update it if you know the correct method.

The following demo uses exactly this matrix for rotation. As you can see, it is smooth and accurate.
https://www.youtube.com/watch?v=cWCYTX--Hd4

### CODE REVIEW

**Comment by vladmandic** [comment]
@ButzYung nice PR, just few comment:
- meshRaw recalculation is not a bad thing, but to be consistent, then boxRaw should be updated as well
  it's both or neither as meshRaw is relative to boxRaw
- clearly matrix has a good use-case (as it fits GL use-case), but so does angle (for anyone that doesn't use GL rotation)  
  suggest to return both in a rotation object
  so return object of a `calculateFaceAngle` can be `{ angle, matrix }`
- user will not know how to use rotation matrix - saying `which directly fits three.js Matrix4.fromArray function` is a start,  
  but having a demo that uses matrix would help a lot. perhaps extend a demo in `demo/browser.js` to draw a point cloud
  with 3D rotations as you have in the posted video?
  or a completely separate demo. honestly, I never played with `three.js` and it would help me a lot as well

**Comment by vladmandic** [comment]
@ButzYung sorry, ignore silly comment on meshRaw and boxRaw as mesh is not relative to box, it's relative to input image. so cropping coordinates of meshRaw basically makes it relative to face only which means it cannot be displayed in the context of input image or in reference to other model outputs. meshRaw cannot be cropped in the library. if needed, that can be done by user in the app. 

other comments are still valid.

**Comment by ButzYung** [comment]
@vladmandic  The reason why I proposed `meshRaw` at the beginning is that there is such a need for a version of mesh in which the xyz coordinates are proportional and independent of the box/image size (`mesh`'s coordinates are not proportional since z is unscaled, and xy are dependent on the box/image size). But then you are right on the fact that the processing can be done on the app side (which is what I have been doing), and so now I just leave the original `meshRaw` intact. The only thing changed in `facemesh.ts` is the `box` part with the width and height fixed.

After some online searching, I have found that there are actually ways to transform rotation matrix to euler angles without going through the full and more complex routine (matrix => quaternion => euler). Although not as "accurate" as the full routine, the resulting angles are still good without importing a full math library. Therefore the new angle now outputs the original pitch/yaw/roll as well as the rotation matrix, without breaking any existing config.

That demo is my app which uses `human` for the face AI part, just to show that the rotation returned by this new routine is accurate.

**Comment by vladmandic** [comment]
i'll merge this PR, but will change the output format as  I don't like combining angles and matrix in a single flat object  
will need to check for performance impact, but i don't think it will be significant  
and will run few tests to see how are new angles performing vs old way

**Review by vladmandic — APPROVED** [review]

**Comment by vladmandic** [comment]
Couple of changes on top of your PR:
- Big change is format of output  
  `{ rotation: { angle, matrix }`
- Documentation
  Add notes to wiki/Outputs.md
- Needed to normalize Euler angles to full circle as rotation matrix is in Pi/2 space  
  For example, face sideways should result in 90 degrees, not 45 degrees  
- Typo that went throughout the code  
  It's `roll`, not `row` :)
- No named functions inside anonymous function  
  Switched helper functions to anonymous format
- Unnecessary assignments such as returning array and then converting to object later  
  Changed so function returns object directly
- When disabling ESlint rule, be specific not generic disable  
  E.g., "// eslint-disable-next-line no-unused-vars, @typescript-eslint/no-unused-vars"
- ESLint complaining on non-strict types for fixed array

I left original angle function in the code so i can switch to it if needed  

Overall, yes, precision does look better: very simmilar for pitch and yaw, but definitely better for roll  
Comparing Euler angles (in degrees) for matrix-based calculation vs simple-calculation:
- Pitch: Looking up: -46 vs -64 Looking down: +61 vs +68
- Yaw: Looking left: -94 vs -83 Looking right: +75 vs +79
- Roll: Facing left: -29 vs -7 Facing right: 15 vs 2

Thanks for the PR!

It's in main branch now, but since this is a breaking change,  
it will be released in v1.3 instead of pushing minor update

**Comment by Shubhambindal2017** [comment]
@ButzYung @vladmandic Thanks for this awesome library, just a question why do we need to multiply each of -thetaX, -thetaY and -thetaZ by '2' inorder to get pitch, yaw and roll respectively? Isn't -thetaX, -thetaY and -thetaZ itself the pitch, yaw and roll (euler angles)?

`return { pitch: 2 * -thetaX, yaw: 2 * -thetaY, roll: 2 * -thetaZ };`

[https://github.com/vladmandic/human/blob/main/src/face/angles.ts#L81](url)

I am asking this based on these references:
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.transform.Rotation.html
- https://github.com/natanielruiz/deep-head-pose/blob/master/code/datasets.py#L540:L544
- https://github.com/google/mediapipe/issues/1561#issuecomment-771027016

**Comment by vladmandic** [comment]
thanks!  

i dont think its different - in the samples you've quoted, inputs are normalized 2x before calculations  
are the results incorrect?

**Comment by ButzYung** [comment]
@Shubhambindal2017 @vladmandic I have done a comparison between the angles returned by `human` and the angles calculated from the rotation matrix using another method (matrix => quaternions => eulers), and I think the 2x multiplification is unnecessary.

**Comment by vladmandic** [comment]
I'll run some tests and if confirmed, I'll remove 2x - target EOW.

**Comment by Shubhambindal2017** [comment]
Thanks @vladmandic, but I doubt that removing 2x will also cause the angles (yaw/pitch/roll) to be halved of what the current 'human' gave as output ; will wait for your test results.

Btw @ButzYung if possible can you please the code snippet of another method (matrix => quaternions => eulers) that you used to get angles from the rotation matrix.

**Comment by ButzYung** [comment]
@Shubhambindal2017 I use the `three.js` library for the conversions.

Quaternion.setFromRotationMatrix
https://github.com/mrdoob/three.js/blob/dev/src/math/Quaternion.js

Euler.setFromQuaternion
https://github.com/mrdoob/three.js/blob/dev/src/math/Euler.js

It seems the newer version of `three.js` is doing Euler.setFromQuaternion by turning the quaternion to a rotation matrix and then euler angles. For some reasons I am using the math library from an old version of `three.js` and they have a direct quaternion => euler function, but the results returned from these methods are basically the same.

**Comment by vladmandic** [comment]
change is validated and will be included in human 2.5.4 scheduled for this friday

**Comment by Shubhambindal2017** [comment]
@vladmandic but removing 2x will also make the yaw/pitch/roll halved (to what current 'human' output) right? (Please confirm whether I am right or not - based on your test results.) 
If yes, then will those values of yaw/pitch/roll be correct? Example - I think after removing 2x, if we move face left/right 90* then yaw will be close to +-45* (it will not reach a value of 90* - what ideally it should output).

**Comment by vladmandic** [comment]
@Shubhambindal2017 a) any angle more than 45 degrees is inaccurate by definition since face parts get obstructed and approximations start to go wild, b) which is it? you started this thread yesterday asking to remove 2x?

**Comment by Shubhambindal2017** [comment]
actually, I started this thread to understand why the angles are multiplied by 2, as by definition/logic it should not be multiplied. But at the same time it also true that by removing it, all the angles will now be halved. Is there any evaluation strategy that you use to evaluate performance of yaw/pitch/roll?

**Comment by vladmandic** [comment]
for any 3d use, rotation matrix is far better than using rotation angles. angles are mostly for informative purposes.
as there is no concensus, i'll leave the code as it was.

**Pull request merged**
